package:
  name: dasel
  version: 3.3.1
  epoch: 0
  description: CLI tool for querying and modifying YAML/JSON/etc
  copyright:
    - license: MIT

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  # checkout the dasel source at v3.3.1
  - uses: git-checkout
    with:
      repository: https://github.com/TomWright/dasel
      tag: v${{package.version}}

  # build the CLI binary
  - runs: |
      CGO_ENABLED=0 go build -o dasel ./cmd/dasel

  # install into the package directory
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin
      install -m755 dasel ${{targets.destdir}}/usr/bin/dasel

test:
  environment:
    contents:
      repositories:
        - packages
        - https://packages.wolfi.dev/os
      keyring:
        - melange.rsa.pub
        - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
      packages:
        - busybox
        - dasel
  pipeline:
    - runs: |
        VERSION=$(/usr/bin/dasel version)
        if [[ "$VERSION" == *"v3.3.1"* ]]; then
          echo "PASS: Package is based on dasel version 3.3.1"
        else
          echo "FAIL: Package is not based on dasel version 3.3.1"
          exit 1
        fi

        NORMAL_INPUT="users:
            - &mohammad
              name: Mohammad
              following: []

            - &sally
              name: Sally
              following:
                - *mohammad"
        
        NORMAL_EXPECTED="users:
            - name: Mohammad
              following: []
            - name: Sally
              following:
                - name: Mohammad
                  following: []"
        
        NOR_RESULT=$(echo "$NORMAL_INPUT" | /usr/bin/dasel query --in yaml)
        if diff -u <(echo "$NOR_RESULT") <(echo "$NORMAL_EXPECTED"); then
          echo "PASS: Normal YAML parsed as expected."
        else
          echo "FAIL: Failed to parse normal YAML."
          exit 1
        fi


        MALICIOUS_INPUT="users:
            - &mohammad
              name: Mohammad
              following:
                - *mohammad"
        
        set +e
        echo "$MALICIOUS_INPUT" | /usr/bin/dasel query --in yaml > /dev/null 2>&1
        STATUS=$?
        set -e

        if [ "$STATUS" -eq 0 ]; then
          echo "FAIL: Malicious YAML unexpectedly accepted. Expected vulnerable recursive expansion failure."
          exit 1
        fi

        echo "PASS: Malicious YAML triggered failure as expected."
        echo "All tests completed successfully."
        # We could check if the output contains "stack overflow" or "goroutine stack exceeds",
        # but we decided not to depend on runtime errors that are not part of our source code.
        # The error is printed to the std for visual/manual check too.